// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkikgsfbwhlzassknnun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraWtnc2Zid2hsemFzc2tubnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzQ3NTMsImV4cCI6MjA2MjgxMDc1M30.mxBjQwgBxljnf_8HBe8Zc9VTuANvKIZ0-7fj6oCv9cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);